
exports.STATES = [
    //PUB
    "moi ce bot de Lotharie 👓",
    "francememes.com",
    "francememes.com",
    "francememes.com",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le stream de Lotharie sur twitch.tv/lotharie !",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    "le Twitter de FRANCE MEMES, trodébar ! - https://twitter.com/francememes_",
    
    //MEMES
    "si Lotharie ne se chie pas dessus...",
    "pas ta mère ! UwU", 
    "2 Girls, 1 Cup",
    "Jean Castex stream sur Twitch",
    "bb Sardoche <3",
    "la vidéo react de Pyrorca depuis 5h",
    ", un modo sauvage apparaît !",
    "une guerre civil créé par les admins.",
    "pas Boku No Pico du tout.",
    "Devilman Crybaby, pcq c'est son anime préféré.",
    "Gérard démonter la chinoise qui ressemble à Xavier.",
    "le guide utilisateur d'une AK-47.",
    "ta daronne se faire démonter par le chieng de FM.",
    "LA TM CUP de ZERATOR PCQ C'EST TROP BIEN WTF",
    "si Kermit ne serait pas intelligent dans le dernier pourcentage de son cerveau.",
    "le channel #🍑nsfw disponible au niveau 5, car il est un petit cochon.",
    "là-bas voir si j'y suis.",
    "si Pornhub est fermé à cause de l'état.",
    "Macron avoir sa nouvelle propagande sur la chaîne de McFly et Carlito",
    "Game of Thrones sur Salto",
    "son plat de lasagnes en train de réchauffer !",
    "sa nouvelle paire de TN",
    "ça, OH très futé de ta part !",
    "avec tes mains et touche avec tes yeux.",
    "il est RÉMI, bouuuuuuuuuuuh !",
    "! je joue avec mon zgueg !",
    ", traverse la rue et tu trouveras du travail.",
    "la vraie fin de One Piece sur Crunchyroll (et ouais)",
    "Siphano insulter des arabes sur Fallen Kingdom",
    "Théorus chié devant GeminiMan.",
    "le speedrun de Adibou Any%",
    "Maman, je passe à la télé !",
    "par la fenêtre, si il ne croise pas Squalala dans les airs",
    "son ex l'ayant quitté hier. :'(",
    "si Blyat est encore mute",
    "dans la grosse chaussette où Squalala s'est branlé",
    "la biscotte de Squalala",
    "lotha bourré au rosé...",
    "c'est encore un troll de pozor"

];